### ISSUE TITLE
Full Project File Redesign

### ISSUE THREAD

**Issue by nautonsatwit** [martiniratwit/Dyson-Sim#17]
Fix the files in the src folder by attempting to follow a MVC architecture. Need to:
Keep all visual elements in View
Enable streamlined communication between View and Model through the Controller
Allow Model to determine what to display to the Controller

System still launched through View, as View extends the Application class

**Comment by forkaholic** [comment]
commit: 2e80ec52f47b97a85e95474cd1c6c510b72e229d
